version: "3.7"

services:
  mariadb:
    image: mariadb
    container_name: chomchob-testing-wallet-api
    restart: always
    environment:
      DB_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - docker-service

networks:
  docker-service:
    driver: bridge
